plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - gemfiles/*
  NewCops: enable

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf

Layout/LineLength:
  Max: 128

Metrics/BlockLength:
  Exclude:
    - rekkyo.gemspec
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*


RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
