---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.0
gemfile:
  - Gemfile
  - gemfiles/activesupport_5.1.gemfile
  - gemfiles/activesupport_5.2.gemfile
before_install: gem install bundler -v 1.17.1
