name: Build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.5', '2.6', '2.7', '3.0', '3.1']
        activesupport: ['5.2', '6.0', '6.1', '7.0']
        experimental: [false]
        exclude:
          - ruby: '2.5'
            activesupport: '7.0'
          - ruby: '2.6'
            activesupport: '7.0'
          - ruby: '2.7'
            activesupport: '5.2'
          - ruby: '3.0'
            activesupport: '5.2'
          - ruby: '3.1'
            activesupport: '5.2'
    continue-on-error: ${{ matrix.experimental }}
    env:
      APPRAISAL: activesupport_${{ matrix.activesupport }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: |
        bundle install
        bundle exec appraisal $APPRAISAL bundle install
    - name: Run tests
      run: bundle exec appraisal $APPRAISAL rake
